// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/*";
  };
  "pages/Index.tsx": {
    id: "pages/Index";
    page: "/";
  };
  "pages/NotFound.tsx": {
    id: "pages/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/Index": typeof import("./app/pages/Index.tsx");
  "pages/NotFound": typeof import("./app/pages/NotFound.tsx");
};