import { createRequestHandler } from "@react-router/cloudflare";

// Import the build object generated by 'react-router build'
// @ts-expect-error - this file is generated at build time
import * as build from "../build/server/index.js";

const requestHandler = createRequestHandler(build);

export default {
  async fetch(request, env, ctx) {
    return requestHandler(request, {
      cloudflare: { env, ctx },
    });
  },
} satisfies ExportedHandler;
